<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows7.0</TargetFramework>
    <RootNamespace>MultiplayerBox_Client</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platforms>AnyCPU;x64;x86</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="ModInfoTransfer">
      <HintPath>..\ModInfoTransfer\bin\Debug\net10.0\ModInfoTransfer.dll</HintPath>
    </Reference>
    <Reference Include="NetLiblary">
      <HintPath>..\NetLiblary\bin\Debug\net10.0\NetLiblary.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
